### ISSUE TITLE
v0.19.0-1 QA Review

### ISSUE THREAD

**Issue by smashwilson** [atom/github#1641]
QA Review to prepare for the v0.19.0 release. Let's build Atom with the v0.19.0-1 prerelease version of this package and ensure that all of the bugs we wanted to fix are fixed properly, and that there are no unexpected complications from snapshotting or asar-bundling.

The work we're testing can be found in [the merged column of the project board for this sprint](https://github.com/atom/github/projects/11#column-2928440).

##### Checklist

- [x] #1637 - There should be no `npm audit` findings from dependencies of atom/github.
- [x] #1607 - PR Meta Infos
- [x] #1440 + #1635 - Undo an initial commit
- [x] #1241 + #1634 - No exception when using context menu to stage or unstage with no selection
- [x] #1312 + #1633 - No "mode change" banner on file patches for added or deleted executable files
- [x] #1229 + #1632 - Discarding rapidly from the staging view throws an exception
- [x] #1602 - No "preview" in GitHub tab
- [x] #1490 + #1631 - No stack traces from focus restoration code
- [x] #1614 + #1629 - Focus the Git tab when activating the right dock
- [x] #1589 - Additional links to .com from PR detail panes
- [x] #1601 - Restyled hovercards on PR detail panes
- [x] #1627 - Clicking the "init" button in the Git tab should default to the current working directory
- [x] ✅ from CI in atom/atom#17831
