### ISSUE TITLE
v0.18.3-0 QA Review

### ISSUE THREAD

**Issue by smashwilson** [atom/github#1644]
QA Review to prepare for the v0.18.3 release. Includes backported pull requests listed in #1643.

##### Checklist

- [ ] #1639: Proxy items need to be more resilient to unexpected properties
- [ ] #1637: Use my fork of atom-mocha-test-runner
- [x] #1635: Undo an initial commit
- [ ] #1634: Don't attempt to stage or unstage with no selection
- [ ] #1633: Don't detect executable mode changes on added or deleted files
- [x] #1632: Detached DOM nodes have no parents
- [x] #1631: Prevent race conditions in focus management code (0.18-releases)
- [x] #1629: Activate the git tab on item activation
- [x] #1627: 🐛 Fix default dir for git repo init
- [ ] ✅ from CI on atom/atom#17860.

**Comment by smashwilson** [comment]
Ah, looks like I need to cherry-pick 520b11f7 to be `npm audit` clean.
