### ISSUE TITLE
v0.18.3-1 QA Review

### ISSUE THREAD

**Issue by smashwilson** [atom/github#1645]
QA Review to prepare for the v0.18.3 release. Includes backported pull requests listed in #1643.

##### Checklist

- [x] #1637 + #1596: `npm audit` clean
- [x] #1639: Proxy items need to be more resilient to unexpected properties
- [x] #1635: Undo an initial commit
- [x] #1634: Don't attempt to stage or unstage with no selection
- [x] #1633: Don't detect executable mode changes on added or deleted files
- [x] #1632: Detached DOM nodes have no parents
- [x] #1631: Prevent race conditions in focus management code
- [x] #1629: Activate the git tab on item activation
- [x] #1627: 🐛 Fix default dir for git repo init
- [x] ✅ from CI on atom/atom#17860.

**Comment by smashwilson** [comment]
Tagged as v0.18.3.
