### ISSUE TITLE
Stuff we should add to core for a better git package

### ISSUE THREAD

**Issue by benogle** [atom/github#18]
Rather than drag people from the core team away from their current work, it might make sense for the folks working on this package to do these:
- [ ] [Install Atom Packages from Git URLs](https://github.com/atom/apm/issues/355) - to allow easy github-internal distribution 
- [x] [Using atom-text-editor in packages](https://github.com/atom/atom/issues/5503) - to enable a not crappy commit box
- [ ] [Allow panels to have multiple items](https://github.com/atom/atom/issues/10897) - to allow all the panels specified by @simurai 
- [ ] Handle atom:// urls correctly on all platforms [related issue 1](https://github.com/atom/atom/issues/2037) - [related issue 2](https://github.com/atom/atom/issues/5262) - to allow seamless oauth and "open in atom" button on .com

Feel free to add more to this; these are off the top of my head.
