### ISSUE TITLE
v0.23.0-0 QA Review

### ISSUE THREAD

**Issue by vanessayuenn** [atom/github#1806]
Here is a list of all the PRs going out in [this release](https://github.com/atom/github/releases/tag/v0.23.0-0). Most of them don't have verification steps, so we only need to test the ones below:

- [x] #1767: Commit Preview
- [x] #1797: Prevent broken patches when staging or unstaging lines rapidly
- [x] #1756: Re-introduce commit message template
- [x] #1512: Render file patches with a decorated Editor

- [x] ✅green CI on atom/atom#18478 

-----
I am just leaving the untestable PRs here for reference. 

Docs
#1725: RFC for Pull Request Review III
#1753: RFC for multi-file diff
#1746: Process proposal
#1766: Fix broken links in react-component-classification.md
#1750: Update RFC process, add blog post blurb section to RFC template

Tests
#1765: Retry known test flakes

Build & dependencies updates
#1789: Coveralls Part XVIII
#1740: Move CI to Azure Pipelines
#1757: Update dugite to 1.79.0
#1798: Update Enzyme and the React adapter
#1790: Update node-fetch to the latest version 🚀
#1755: Update event-kit to the latest version 🚀
#1778: Update node-fetch to the latest version 🚀

**Comment by annthurium** [comment]
a couple of things:

- Vanessa found some rendering glitches which we decided with the team are not release blockers.  Will file separate issues for them.

-While QA testing https://github.com/atom/github/pull/1512 I came across a known regression of https://github.com/atom/github/issues/1241 which is also not a ship blocker.

**Comment by Lordevss** [comment]
![dac3dcb2-089a-11e7-9b92-dcdf9791d52d](https://user-images.githubusercontent.com/28796752/49336709-6b05f280-f618-11e8-97f9-ea82f4d777c3.png)

**Comment by Lordevss** [comment]
- @
Duplicate of #
