### ISSUE TITLE
v0.24.0-0 QA Review

### ISSUE THREAD

**Issue by smashwilson** [atom/github#1866]
#### Changes to verify

- [ ] #1809: Suppress "Unable to locate git workspace root" error
- [ ] #1808: Add button to show/hide password in credentials dialog
- [ ] #1828: Fix bug where pull request cannot be viewed if `pullRequest.headRepository` is null
- [ ] #1822: Fix: git tab keeps popping open when there's a merge conflict
- [ ] #1807: View commit details in pane
- [ ] #1847: Backportable keymap changes
- [ ] #1829: Add tab for all changed files in a pull request
- [ ] #1854: Handle renames on files changed tab
- [ ] #1859: Adjustable diff font size
- [ ] #1855: Fix: wrong prefix on PR files changed
- [ ] #1805: Commit preview tweaks
- [ ] Clean CI check on atom/atom#18641

#### Other changes in this release

* #1810: Update screenshots
* #1811: Process iteration
* #1804: Split IssueishDetailView into IssueDetailView and PullRequestDetailView
* #1826: Moving to CodeCov
* #1827: Disable the "changes" status from CodeCov
* #1831: Move the multi-file diff RFC to "feature requests" with the others
* #1836: Enzyme and Enzyme adapter upgrade
* #1799: Update event-kit to the latest version
* #1777: Update tree-kill to the latest version
* #1837: No need for AppVeyor reporter
* #1772: Update relay-compiler to the latest version
* #1843: Build PRs that only change documentation
* #1838: Bring our GraphQL schema up to date
* #1845: Pin CodeCov package to the latest master
* #1842: Fix React component atlas
* #1846: Update temp to the latest version
* #1849: Remove status section from feature proposal template
* #1851: Update what-the-diff to the latest version
