### ISSUE TITLE
v0.24.0-1 QA Review

### ISSUE THREAD

**Issue by smashwilson** [atom/github#1870]
#### Changes to verify

- [x] #1809: Suppress "Unable to locate git workspace root" error
- [x] #1808: Add button to show/hide password in credentials dialog
- [x] #1828: Fix bug where pull request cannot be viewed if `pullRequest.headRepository` is null
- [x] #1822: Fix: git tab keeps popping open when there's a merge conflict
- [x] #1807: View commit details in pane
- [x] #1847: Backportable keymap changes
- [x] #1829: Add tab for all changed files in a pull request
- [x] #1854: Handle renames on files changed tab
- [x] #1859: Adjustable diff font size
- [x] #1855: Fix: wrong prefix on PR files changed
- [x] #1805: Commit preview tweaks
- [x] #1869: UserStore handles GitHub remotes that no longer exist
- [x] Clean CI check on atom/atom#18641

#### Other changes in this release

* #1810: Update screenshots
* #1811: Process iteration
* #1804: Split IssueishDetailView into IssueDetailView and PullRequestDetailView
* #1826: Moving to CodeCov
* #1827: Disable the "changes" status from CodeCov
* #1831: Move the multi-file diff RFC to "feature requests" with the others
* #1836: Enzyme and Enzyme adapter upgrade
* #1799: Update event-kit to the latest version
* #1777: Update tree-kill to the latest version
* #1837: No need for AppVeyor reporter
* #1772: Update relay-compiler to the latest version
* #1843: Build PRs that only change documentation
* #1838: Bring our GraphQL schema up to date
* #1845: Pin CodeCov package to the latest master
* #1842: Fix React component atlas
* #1846: Update temp to the latest version
* #1849: Remove status section from feature proposal template
* #1851: Update what-the-diff to the latest version

**Comment by smashwilson** [comment]
Holding the release until we can fix #1868.

**Comment by robertrossmann** [comment]
Not sure if this is the right place to report QA-related feedback, but here some some issues and general suggestions. Let me know if you'd like me to split these into separate issues. 😇

#### Pull request tabs' titles have selectable text

![screenshot 2019-01-03 at 11 43 15](https://user-images.githubusercontent.com/3058150/50633872-1c1be780-0f4d-11e9-8b8e-69e0c529512b.png)

---

#### Spacing before `Show more` on a commit message

While looking at pull request details => commits, the `Show more` button is too close to the commit message.

![screenshot 2019-01-03 at 11 42 06](https://user-images.githubusercontent.com/3058150/50634065-ba0fb200-0f4d-11e9-83b4-72864238cc76.png)

---

#### Opening very large diffs from the "Recent commits" _actually opens_ the very large diff

I think there used to be that `Diff too large` warning when I click on a file with staged changes with too many lines - not sure if that's been removed or if this is a regression, but for diffs with tens of thousands of changed lines Atom still becomes very unresponsive while rendering the diff.

**Steps to reproduce:**

1. Clone the `tree-sitter-javascript` project and open this commit in Atom: https://github.com/tree-sitter/tree-sitter-javascript/commit/1996b31e237192b0d9aeca2c8c02f041dcfb7e29
1. Observe Atom hanging for several minutes while rendering the diff

**Expected behaviour:**

Github detects a large diff and skips rendering the diff for large files or warns before opening the diff pane

---

## UI/UX suggestions

#### Show committer's name in commit details pane

I usually recognise my co-workers/fellow open-sourcerers by their names, or by their Github handles. I would prefer to see at least the committer's name in the commit details pane.

> Stretch goal: show a card on hover with additional information fetched from Github ([inspiration](https://atom.io/packages/github-user-datatip))

![screenshot 2019-01-03 at 12 01 06](https://user-images.githubusercontent.com/3058150/50634615-9483a800-0f4f-11e9-9796-374a7e486487.png)

---

#### Add a `Copy commit shasum` button wherever a shasum is shown in commit details panes

Being able to copy the commit shasum would be great for continuing my work in other tools (ie. the git CLI). This could be especially useful on the pull request details pane.

![screenshot 2019-01-03 at 12 08 46](https://user-images.githubusercontent.com/3058150/50634991-ba5d7c80-0f50-11e9-98f0-df6e012bfd7c.png)

![screenshot 2019-01-03 at 12 12 14](https://user-images.githubusercontent.com/3058150/50635054-f55fb000-0f50-11e9-8684-7428f9a2b530.png)

> Alternatively, show the full commit shasum as text somewhere so the user can copy it manually.

---

Hopefully you'll find this feedback useful. Nice work! ❤️

**Comment by smashwilson** [comment]
@robertrossmann Oh wow, thanks! This is super thorough and helpful.

> Not sure if this is the right place to report QA-related feedback [..]

You're right, I think we'd prefer to track these as separate issues rather than grouping them all here. You've already taken the trouble to write it all up, though, so I can handle the splitting :smile:

These [QA issues](https://github.com/atom/github/issues?utf8=%E2%9C%93&q=is%3Aissue++label%3Aquality+) are part of [the way we ship](https://github.com/atom/github/blob/master/docs/how-we-work.md#how-we-ship) - they're intended to be a final, simple smoke test to ensure that all of the bugs and features we _think_ we're releasing still actually work once we tag a release and include it in a full Atom build as a bundled module distributed within Atom's startup snapshot. Historically, we've had a few pretty bad problems that almost made it to release because they were hidden by our usual testing M.O. of [installing the package non-bundled from git, and linking it in dev mode](https://github.com/atom/github/blob/master/CONTRIBUTING.md#getting-started). With that in mind, I'll hold up 0.24.0 tag for the graphical glitches you've found, but the others we'll keep as issues for a future sprint to keep our release scope from creeping.

**Comment by robertrossmann** [comment]
Thank you @smashwilson for the explanation - in the future, I'll open up separate issues for all of these. ❤️

**Comment by smashwilson** [comment]
Next release candidate QA checklist: #1879
