### ISSUE TITLE
v0.23.2-0 QA Review

### ISSUE THREAD

**Issue by smashwilson** [atom/github#1883]
Backported bugfixes from v0.24.0 onto the v0.23.0 release line.

#### Changes to verify

- [x] #1871: Cache token scope check failures
- [x] #1869: UserStore handles GitHub remotes that no longer exist
- [x] #1847: Backportable keymap changes
- [x] #1828: Fix bug where pull request cannot be viewed if pullRequest.headRepository is null.
- [x] #1809: Suppress "Unable to locate git workspace root" error

#### Other changes in this release

_N/A_
