### ISSUE TITLE
v0.25.0-0 QA Review

### ISSUE THREAD

**Issue by kuychaco** [atom/github#1936]
Included PRs:
- [x] #1856: Fetch and display readonly inline comments
Most testing done with https://github.com/kuychaco/test-repo/pull/5/files
  - [x] PRs with a large # of reviews and comments should load in a reasonable amount of time (tested first 6 PRs in each of the two lists (12 total) contained here https://github.com/github/analytics/pull/454#issuecomment-382155693)
  - [ ] ⚠️  ensure that comment thread order is retained when viewing a pull request that has paginated comments and reviews (that is, if there are multiple comment threads, the threads show up in the right order) (see #1944)
  - [x] ensure that comment order within a thread is retained when viewing a pull request that has paginated comments and reviews
  - [x] ensure that comments are positioned on the same line of the diff as they are on github dotcom
  - [x] single comments (that are NOT part of a review) should show up
  - [ ] ⚠️ resolved comments should not show up (see #1973)
  - [x] outdated comments should not show up
  - [ ] ⚠️ replies to resolved comments should not show up (see #1937)
  - [x] hidden comments and their replies to show up correctly (as they do on dotcom)
  - [x] replies to outdated comments should not show up
  - [x] replies to deleted stand-alone comments should not show up (like on dotcom)
  - [x] replies to deleted comments in reviews show up (like on dotcom)
- [x] #1902: make commit message template ignore commented lines
- [x] #1922: Find and replace integration
- [x] #1906: add committer name to commit detail pane
- [x] #1927: Visual tweaks to Github's Remote Selector & No Remote views

PRs without verification steps:
* #1903: Correct remaining flapping test coverage
* #1900: Test coverage for GitShellOutStrategy
* #1901: Test coverage for GitTempDir
* #1896: Upgrade Globby
* #1893: Upgrade dugite
* #1894: Upgrade moment
* #1891: Update all of our dev dependencies in one fell swoop
* #1884: Upgrade to the latest react and react-dom
* #1885: Synchronize electron-link and electron-mksnapshot versions to Atom's

- [ ] clean CI check on https://github.com/atom/atom/pull/18787

**Comment by kuychaco** [comment]
While QA testing #1856 I caught https://github.com/atom/github/issues/1937 (resolved comment showing up in Changed Files tab). In my opinion this isn't necessarily release blocking. @annthurium @smashwilson what do you think? 💭

**Comment by kuychaco** [comment]
Non-blocking styling issue -- https://github.com/atom/github/issues/1943

**Comment by kuychaco** [comment]
Okay #1943 is much more than a styling issue... it's that we're not handling pending comments correctly. What do y'all think? Is this blocking? I err on the side of "no"

**Comment by kuychaco** [comment]
Also found that multiple threads on the same line don't appear in the correct order -- #1944

**Comment by kuychaco** [comment]
Found an edge case where comments in a thread don't show up correctly -- #1945 🤔

**Comment by kuychaco** [comment]
While testing a bunch of PRs with lots of comments/reviews I hit an error that broke the PR pane item -- #1946

**Comment by annthurium** [comment]
IMO none of these are release blocking.

thanks Katrina!

**Comment by smashwilson** [comment]
I agree that none of these are blocking. The review comments model is complicated enough (and has evolved enough over time) that I'm guessing we'll be seeing new, progressively weirder edge cases for quite some time.

👍 :shipit:

**Comment by kuychaco** [comment]
Note: master moved forward after cutting this pre-release and actually publishing... @smashwilson and I decided to just include the [newly merged things](https://github.com/atom/github/compare/56847e3691ad220a3d4b81744ce5564cbf09f1ed...2c4b288c1bbd1d8611c74204216296f924fcc0f9) since they were pretty low-risk (dependency upgrade and cosmetic logo changes). 

This published release associated with 0.26.0 (accidentally skipped a minor version due to apm publishing complications).
