### ISSUE TITLE
v0.27.0-0 QA Review

### ISSUE THREAD

**Issue by vanessayuenn** [atom/github#2005]
### Changes to verify 
- [x] #2003: Remove commit ID field from graphql query fragment
- [x] #1913: collapse large diffs && collapse/expand any diff within multi file patch view 
  - [x] 🐛  ~**[release blocking bug]** #1946 comments in diff-gated filepatch in PR view cause crashing~ fixed by #2007 
  - [ ] 🐛 #2006 mode change but empty file change patch behaves weirdly being expanded/collapsed
  - [ ] 🐛 #2008 comment positionings are wrong when there are diff gated patch in PR
- [x] #1989: Suggested changes styling
- [x] #1985: support new reaction emoji from GitHub.com
- [x] #1988: respect `core.commentChar` from git settings.
- [x] #1949: Diff color tweaks

#### Docs changes and dep upgrades also included in this release
- #1897: PR Review Feature Request: review comment changes
- #1959: Retry flaky Repository test
- #2002: Update eslint to the latest version 🚀
- #2001: Update dugite to the latest version 🚀
- #2000: Update sinon to the latest version 🚀
- #1999: Update globby to the latest version 🚀
- #1998: Update eslint to the latest version 🚀
- #1997: Update sinon to the latest version 🚀
- #1994: Update dugite to the latest version 🚀
- #1991: Update to @atom/mocha-test-runner and mocha@6.0.2
- #1990: Update sinon to the latest version 🚀
- #1987: Update drifting dependencies
- #1982: Upgrade to Relay 3.0.0
- #1980: react@16.8.3
- #1966: eslint@5.14.1
- #1967: keytar@4.4.0
- #1956: React upgrades
- #1963: Update babel-plugin-istanbul to the latest version 🚀
- #1964: Update sinon to the latest version 🚀
- #1957: Update prop-types to 15.7.2
- #1954: CodeCov package upgrade
- #1955: Update nyc to the latest version 🚀
- #1938: Minor tweaks to release process
