### ISSUE TITLE
v0.29.0-0 QA Review

### ISSUE THREAD

**Issue by smashwilson** [atom/github#2129]
### Changes to verify

- [x] #2117: Group resolved comments
- [x] #2115: swap button colors to emphasize `Comment` more than `Resolve Conversation`
- [x] #2100: Handle ghost users (deleted accounts)
- [x] #2104: Get author info tooltips working again
- [x] #2105: Don't pass destroyed TextEditors to find-and-replace
- [x] #2084: Additional entry point for review comments
- [x] #2085: Add author association to review summaries and thread comments
- [x] #2086: Allow :/ in remote URL
- [x] #2074: Prefill some metadata for report abuse link in review comments
- [x] #2066: Hide alt text when committer's avatar fails to load
- [x] #2057: Indicate that comment has been edited

#### Other changes

* #2127: Schema-up action, iteration N+1
* #2095: Feature Request: Review author flow
* #2125: Default upstream refspec to master
* #2108: GitHub Actions to automate our GraphQL schema management
* #2113: Add `NODE_ENV=development` to `test` script to see React errors
* #2107: Exclude deprecated fields from the fetched schema
* #2091: Bump babel-plugin-istanbul from 5.1.2 to 5.1.3
* #2083: Bump mocha from 6.1.3 to 6.1.4
* #2082: Bump sinon from 7.3.1 to 7.3.2
* #2080: Bump mocha-junit-reporter from 1.21.0 to 1.22.0
* #2079: Bump whats-my-line from 0.1.1-0 to 0.1.1
* #2076: Bump babel-plugin-istanbul from 5.1.1 to 5.1.2
* #2075: Bump nyc from 13.3.0 to 14.0.0
* #2072: whitelist a bunch of dependencies (or: Let's Trust Bots To Not Mess Things Up)
* #2061: Bump enzyme from 3.8.0 to 3.9.0
* #2060: Bump mocha from 6.1.1 to 6.1.3
* #2054: Add some new screenshots
