### ISSUE TITLE
v0.30.0-0 QA Review

### ISSUE THREAD

**Issue by smashwilson** [atom/github#2211]
#### Changes to verify

- [x] #2195: Avoid stalls caused by large diffs fetched from GitHub
- [x] #2124: Make review comments editable
- [x] #2128: Improve error handling when offline
- [x] #2102: Include the Checks API in build status

#### Other changes

- #2210: GraphQL schema update
- #2205: Bump lodash from 4.17.11 to 4.17.14 in /actions/schema-up
- #2202: Test runner bump
- #2201: [Security] Bump lodash from 4.17.11 to 4.17.14
- #2200: GraphQL schema update
- #2199: Bump @babel/preset-env from 7.4.3 to 7.5.4
- #2177: GraphQL schema update
- #2186: Bump keytar from 4.7.0 to 4.10.0
- #2171: GraphQL schema update
- #2167: Bump graphql from 14.2.1 to 14.3.1
- #2159: Bump nyc from 14.0.0 to 14.1.1
- #2158: Bump keytar from 4.4.1 to 4.7.0
- #2156: Bump node-fetch from 2.5.0 to 2.6.0
- #2155: Bump codecov from 3.3.0 to 3.5.0
- #2154: GraphQL schema update
- #2153: Bump @babel/generator from 7.4.0 to 7.4.4
- #2152: Bump @babel/plugin-proposal-class-properties from 7.4.0 to 7.4.4
- #2151: Bump @atom/mocha-test-runner from 1.5.0 to 1.5.1
- #2150: :arrow_up: react + react-dom
- #2147: tab styling refactor
- #2131: Add issues and pull requests to the current release project
- #2109: Bump node-fetch from 2.3.0 to 2.5.0
- #2136: GraphQL schema update
- #2133: Always create a pull request for schema changes

**Comment by smashwilson** [comment]
Confirmed ✅
